import { PDFDocument, rgb, type PDFPage } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import fontBytes from './fonts/NotoSans-Regular.ttf';
import coordinatorSignatureBytes from '../public/reimbursement/coordinator-signature.png';
import { organisationName, partnershipAgreementArticles, type SavedPartnershipAgreement } from '../shared/reimbursement';

const navy = rgb(0.03, 0.24, 0.38), paleBlue = rgb(0.82, 0.9, 0.95), ink = rgb(0.03, 0.03, 0.03), grey = rgb(0.4, 0.4, 0.4);
const coordinator = { name: `${organisationName} (IJBK e.V.)`, oid: 'E10404746', country: 'Germany', representative: 'Vidit Goyal', position: 'Chairman', email: 'vidit@ijbk-de.org', phone: '+49 157 58060612' };

export async function generatePartnershipAgreementPdf(data: SavedPartnershipAgreement) {
  const doc = await PDFDocument.create(); doc.registerFontkit(fontkit); const font = await doc.embedFont(fontBytes, { subset: true }); const coordinatorSignature = await doc.embedPng(coordinatorSignatureBytes);
  let page!: PDFPage, y = 0; const margin = 42, width = 511; let bodySize = 9, lineHeight = 11.2, paragraphGap = 4, headingSize = 10.2;
  const clean = (value: string) => value.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
  const wrap = (value: string, maxWidth: number, size: number) => { const result: string[] = []; let line = ''; for (const word of clean(value).split(' ')) { const next = line ? `${line} ${word}` : word; if (font.widthOfTextAtSize(next, size) <= maxWidth) line = next; else { if (line) result.push(line); line = word; } } if (line) result.push(line); return result; };
  const text = (value: string, x: number, yy: number, size = 7.1, color = ink) => page.drawText(clean(value), { x, y: yy, size, font, color });
  const newPage = (size = 9, leading = 11.2, gap = 4, sectionSize = 10.2) => { bodySize = size; lineHeight = leading; paragraphGap = gap; headingSize = sectionSize; page = doc.addPage([595.28, 841.89]); const header = `${data.projectName} | Erasmus+ KA152-YOU | Project ID ${data.projectCode}`; text(header, (595.28 - font.widthOfTextAtSize(header, 7.1)) / 2, 817, 7.1, grey); page.drawLine({ start: { x: margin, y: 803 }, end: { x: margin + width, y: 803 }, thickness: 0.8, color: paleBlue }); y = 780; };
  const paragraph = (number: string, value: string) => { const parts = value.split('\n'); parts.forEach((part, partIndex) => { const prefix = partIndex === 0 ? `${number} ` : '• '; for (const line of wrap(prefix + part, width, bodySize)) { text(line, margin, y, bodySize); y -= lineHeight; } }); y -= paragraphGap; };
  const heading = (value: string) => { y -= 2; page.drawRectangle({ x: margin, y: y - 4, width, height: headingSize + 7, color: paleBlue }); text(value, margin + 6, y, headingSize, navy); y -= headingSize + 7; };
  const bankRow = (label: string, value: string) => { const split = 248, rowHeight = Math.max(24, wrap(value, width - split - 14, 8.3).length * 10 + 10); page.drawRectangle({ x: margin, y: y - rowHeight + 5, width: split, height: rowHeight, borderColor: grey, borderWidth: 0.55 }); page.drawRectangle({ x: margin + split, y: y - rowHeight + 5, width: width - split, height: rowHeight, borderColor: grey, borderWidth: 0.55 }); text(label, margin + 7, y - 9, 8.3); wrap(value, width - split - 14, 8.3).forEach((line, i) => text(line, margin + split + 7, y - 9 - i * 10, 8.3)); y -= rowHeight; };
  const footer = () => doc.getPages().forEach((target, index) => { const value = `Partnership Agreement - Page ${index + 1}`; target.drawText(value, { x: (595.28 - font.widthOfTextAtSize(value, 6.1)) / 2, y: 22, size: 6.1, font, color: grey }); });

  newPage(8.9, 11, 3.5, 10.1); text('PARTNERSHIP AGREEMENT', 176, y, 16, navy); y -= 23; const subtitle = `Erasmus+ KA152-YOU - ${data.projectName}`; text(subtitle, (595.28 - font.widthOfTextAtSize(subtitle, 9.6)) / 2, y, 9.6); y -= 29;
  const identity = [['Coordinator', coordinator.name], ['OID / Country', `${coordinator.oid} / ${coordinator.country}`], ['Coordinator signatory', `${coordinator.representative}, ${coordinator.position}`], ['Partner', `${data.partnerName}, OID ${data.partnerOid}, ${data.partnerCountry.toUpperCase()}`], ['Partner signatory', `${data.legalRepresentativeName}, ${data.legalRepresentativePosition}`]];
  for (const [label, value] of identity) { page.drawRectangle({ x: margin, y: y - 19, width: 192, height: 28, color: paleBlue }); text(label, margin + 7, y - 7, 8.4); wrap(value, 303, 8.4).forEach((line, i) => text(line, 246, y - 7 - i * 10, 8.4)); y -= 30; }
  paragraph('', 'The Coordinator and the Partner are each a “Party” and together the “Parties”. The Parties agree as follows:');
  for (const article of partnershipAgreementArticles.slice(0, 3)) { heading(article.title); for (const [number, clause] of article.clauses) paragraph(number, clause); }

  newPage(8.55, 10.55, 3, 9.8); for (const article of partnershipAgreementArticles.slice(3, 6)) { heading(article.title); for (const [number, clause] of article.clauses) { paragraph(number, clause); if (number === '6.2.') { y -= 3; for (const [label, value] of [['Name of the account holder (Partner organisation):', data.accountHolder], ['Bank name:', data.bankName], ['Address of the bank:', data.bankAddress], ['IBAN:', data.iban], ['SWIFT:', data.swift], ['Currency', data.bankCurrency ?? 'EUR']]) bankRow(label, value); y -= 4; } } }

  newPage(9.7, 12.1, 4.5, 10.7); for (const article of partnershipAgreementArticles.slice(6, 9)) { heading(article.title); for (const [number, clause] of article.clauses) { paragraph(number, clause); if (number === '8.1.') { const columns = [145, 185, 181]; page.drawRectangle({ x: margin, y: y - 15, width, height: 22, color: paleBlue }); ['Contact', 'Coordinator', 'Partner'].forEach((label, i) => text(label, margin + columns.slice(0, i).reduce((a, b) => a + b, 0) + 6, y - 8, 8)); y -= 29; const partner = [data.contactName, data.contactEmail, data.contactPhone], coord = [coordinator.representative, coordinator.email, coordinator.phone]; for (const [label, cLines, pLines] of [['Project Contact', coord, partner], ['Emergency / Safeguarding', ['Same as above'], partner]] as [string, string[], string[]][]) { text(label, margin + 6, y, 7.8); cLines.forEach((line, i) => text(line, margin + columns[0] + 6, y - i * 10, 7.8)); pLines.forEach((line, i) => text(line, margin + columns[0] + columns[1] + 6, y - i * 10, 7.8)); y -= 43; } } } }

  newPage(10.1, 12.7, 5, 11); for (const article of partnershipAgreementArticles.slice(9)) { heading(article.title); for (const [number, clause] of article.clauses) paragraph(number, clause); }
  heading('Signatures'); page.drawRectangle({ x: margin, y: y - 13, width, height: 28, color: paleBlue }); text('For the Coordinator', margin + 8, y - 3, 9.3); text('For the Partner', 310, y - 3, 9.3); y -= 39;
  const signatureRows = [['Organisation: IJBK e.V.', `Organisation: ${data.partnerName}`], [`Name: ${coordinator.representative}`, `Name: ${data.legalRepresentativeName}`], [`Position: ${coordinator.position}`, `Position: ${data.legalRepresentativePosition}`], ['Place and date: Kaiserslautern, Germany, 7 September 2026', `Place and date: ${data.signaturePlace}, ${data.signatureDate}`], ['Signature: _________________________', 'Signature:']];
  for (const [left, right] of signatureRows) { wrap(left, 230, 9.2).forEach((line, i) => text(line, margin + 8, y - i * 11, 9.2)); wrap(right, 238, 9.2).forEach((line, i) => text(line, 310, y - i * 11, 9.2)); y -= 40; }
  page.drawImage(coordinatorSignature, { x: margin + 46, y: y - 4, ...coordinatorSignature.scaleToFit(195, 78) });
  try { const signature = await doc.embedPng(data.signature); page.drawImage(signature, { x: 310, y: y - 4, ...signature.scaleToFit(205, 78) }); } catch { text('Signature unavailable', 310, y, 9); }
  footer(); doc.setTitle(`Partnership Agreement - ${data.partnerName} - ${data.partnerCountry}`); doc.setAuthor(organisationName); return doc.save();
}
