import { useState, type ChangeEvent, type FormEvent, type InputHTMLAttributes } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CheckCircle2, Send } from 'lucide-react';
import { acceptsReimbursements, projects } from '@/data/projects';
import { api, ApiError } from '@/lib/reimbursement-api';
import { Button } from '@/components/ui/button';
import SignaturePad from '@/components/reimbursement/SignaturePad';
import AccessGate from '@/components/reimbursement/AccessGate';
import { partnershipAgreementArticles, partnershipAgreementSchema, partnershipCurrencies, today, type ProjectSettings } from '../../shared/reimbursement';
import NotFound from './NotFound';

const coordinator = { name: 'Internationaler Jugend- und Bildungsverein Kaiserslautern e.V. (IJBK e.V.)', oid: 'E10404746', country: 'Germany', representative: 'Vidit Goyal', position: 'Chairman', email: 'vidit@ijbk-de.org', phone: '+49 157 58060612' };
type AgreementFields = { partnerName: string; partnerOid: string; partnerCountry: string; contactName: string; contactEmail: string; contactPhone: string; iban: string; accountHolder: string; swift: string; bankName: string; bankAddress: string; bankCurrency: typeof partnershipCurrencies[number]; legalRepresentativeName: string; legalRepresentativePosition: string; signerEmail: string; signaturePlace: string; signatureDate: string };

export default function PartnershipAgreement() {
  const { projectId } = useParams(); const project = projects.find(item => item.id === projectId && acceptsReimbursements(item)); const client = useQueryClient();
  const session = useQuery({ queryKey: ['organisation-session', projectId], queryFn: () => api<ProjectSettings>(`/projects/${projectId}/organisation-session`), enabled: !!project, retry: false, refetchOnWindowFocus: false });
  if (!project) return <NotFound />;
  return <div className="page-shell py-10 md:py-16 space-y-8"><Link to={`/projects/${project.id}/partner-dashboard`} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="w-4 h-4" />Back to Partner Dashboard</Link><header className="max-w-4xl space-y-3"><p className="text-sm uppercase tracking-[0.18em] text-primary">{project.title}</p><h1 className="text-3xl md:text-4xl font-semibold">Partnership Agreement</h1><p className="text-sm text-muted-foreground">Read the complete agreement and fill each blank directly inside the document.</p></header>{session.isPending ? <p role="status">Checking project access…</p> : session.isError ? (session.error instanceof ApiError && session.error.status === 401 ? <AccessGate audience="organisation" projectId={project.id} onUnlocked={() => client.invalidateQueries({ queryKey: ['organisation-session', projectId] })} /> : <p role="alert">{session.error.message}</p>) : <AgreementForm key={session.data.country} projectId={project.id} projectName={project.title} settings={session.data} />}</div>;
}

function AgreementForm({ projectId, projectName, settings }: { projectId: string; projectName: string; settings: ProjectSettings }) {
  const [form, setForm] = useState<AgreementFields>({ partnerName: '', partnerOid: '', partnerCountry: settings.country ?? settings.countries[0] ?? '', contactName: '', contactEmail: '', contactPhone: '', iban: '', accountHolder: '', swift: '', bankName: '', bankAddress: '', bankCurrency: 'EUR', legalRepresentativeName: '', legalRepresentativePosition: '', signerEmail: '', signaturePlace: '', signatureDate: today() });
  const [signature, setSignature] = useState(''), [declaration, setDeclaration] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [agreementId, setAgreementId] = useState(''), [requestId] = useState(() => crypto.randomUUID());
  const set = (key: keyof AgreementFields) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm(value => ({ ...value, [key]: key === 'swift' ? event.target.value.toUpperCase() : event.target.value }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); const parsed = partnershipAgreementSchema.safeParse({ requestId, ...form, signature, declaration }); if (!parsed.success) { setError(parsed.error.issues.map(issue => issue.message).join('; ')); return; } setBusy(true); try { const receipt = await api<{ id: string }>(`/projects/${projectId}/partnership-agreements`, { method: 'POST', body: JSON.stringify(parsed.data) }); setAgreementId(receipt.id); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function downloadAgreement() { setBusy(true); setError(''); try { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/partnership-agreements/${encodeURIComponent(agreementId)}/pdf`, { credentials: 'same-origin' }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error || 'The agreement PDF could not be downloaded.'); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = `Partnership Agreement - ${form.partnerName} - ${form.partnerCountry}.pdf`; link.click(); URL.revokeObjectURL(url); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  if (agreementId) return <section className="max-w-2xl rounded-2xl border border-emerald-200 bg-emerald-50/50 p-8 text-center space-y-4"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-700" /><h2 className="text-2xl font-semibold">Partnership agreement submitted</h2><p>The agreement for {form.partnerName} ({form.partnerCountry}) is saved. Only one agreement can be submitted for this project and country.</p><Button type="button" onClick={downloadAgreement} disabled={busy}>{busy ? 'Preparing PDF…' : 'Download signed agreement PDF'}</Button>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
  const input = (key: keyof AgreementFields, label: string, props: InputHTMLAttributes<HTMLInputElement> = {}) => <DocInput id={key} label={label} value={form[key]} onChange={set(key)} {...props} />;
  return <form onSubmit={submit} className="space-y-6"><article className="mx-auto max-w-5xl rounded-sm border bg-white p-4 sm:p-8 md:p-12 text-[13px] leading-[1.45] text-slate-950 shadow-md space-y-3">
    <p className="text-center text-[10px] text-slate-500">{projectName} | Erasmus+ KA152-YOU | Project ID {settings.projectCode}</p><h2 className="text-center text-xl font-bold text-sky-900">PARTNERSHIP AGREEMENT</h2><p className="text-center font-semibold">Erasmus+ KA152-YOU - {projectName}</p>
    <div className="grid grid-cols-[minmax(115px,0.8fr)_2fr] border text-xs"><DocRow label="Coordinator">{coordinator.name}</DocRow><DocRow label="OID / Country">{coordinator.oid} / {coordinator.country}</DocRow><DocRow label="Coordinator signatory">{coordinator.representative}, {coordinator.position}</DocRow><DocRow label="Partner"><div className="grid gap-2 sm:grid-cols-3">{input('partnerName', 'Partner organisation')} {input('partnerOid', 'Partner OID', { maxLength: 40 })}<label className="space-y-1"><span className="block font-semibold">Partner country *</span><select id="partnerCountry" disabled required value={form.partnerCountry} onChange={set('partnerCountry')} className="w-full rounded border border-slate-400 bg-white px-2 py-1.5"><option value="">Select country</option>{settings.countries.map(country => <option key={country}>{country}</option>)}</select></label></div></DocRow><DocRow label="Partner signatory"><div className="grid gap-2 sm:grid-cols-2">{input('legalRepresentativeName', 'Name of legal representative')} {input('legalRepresentativePosition', 'Position')}</div></DocRow></div>
    <p>The Coordinator and the Partner are each a “Party” and together the “Parties”. The Parties agree as follows:</p>
    {partnershipAgreementArticles.map(article => <section key={article.title} className="space-y-1"><h3 className="font-bold text-sky-900">{article.title}</h3>{article.clauses.map(([number, clause]) => <div key={number}><p className="whitespace-pre-line"><strong>{number}</strong> {clause}</p>{number === '6.2.' && <div className="my-3 grid grid-cols-[minmax(130px,1fr)_2fr] border">{[['Name of the account holder (Partner organisation)', input('accountHolder', 'Account holder')], ['Bank name', input('bankName', 'Bank name')], ['Address of the bank', input('bankAddress', 'Bank address', { maxLength: 500 })], ['IBAN', input('iban', 'IBAN')], ['SWIFT', input('swift', 'SWIFT / BIC', { minLength: 8, maxLength: 11 })], ['Currency', <label key="currency" className="block space-y-1"><span className="block font-semibold">Bank account currency *</span><select required value={form.bankCurrency} onChange={set('bankCurrency')} className="w-full rounded border border-slate-400 bg-white px-2 py-1.5">{partnershipCurrencies.map(currency => <option key={currency}>{currency}</option>)}</select></label>]].map(([label, field]) => <div className="contents" key={String(label)}><div className="border p-2 font-semibold">{label}</div><div className="border p-2">{field}</div></div>)}</div>}{number === '8.1.' && <div className="my-3 overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-xs"><thead><tr className="bg-sky-100"><th className="border p-2 text-left">Contact</th><th className="border p-2 text-left">Coordinator</th><th className="border p-2 text-left">Partner</th></tr></thead><tbody><tr><td className="border p-2">Project Contact</td><td className="border p-2 whitespace-pre-line">{coordinator.representative}{'\n'}{coordinator.email}{'\n'}{coordinator.phone}</td><td rowSpan={2} className="border p-2"><div className="space-y-2">{input('contactName', 'Contact name')} {input('contactEmail', 'Email', { type: 'email' })} {input('contactPhone', 'Phone number', { type: 'tel' })}<p className="text-[10px] text-slate-500">These details apply to both Project Contact and Emergency / Safeguarding Contact.</p></div></td></tr><tr><td className="border p-2">Emergency / Safeguarding</td><td className="border p-2">Same as above</td></tr></tbody></table></div>}</div>)}</section>)}
    <h3 className="font-bold text-sky-900">Signatures</h3><div className="grid gap-6 border-t-8 border-sky-100 pt-4 sm:grid-cols-2"><div className="space-y-3"><p className="font-bold">For the Coordinator</p><p>Organisation: IJBK e.V.</p><p>Name: {coordinator.representative}</p><p>Position: {coordinator.position}</p><p>Place and date: Kaiserslautern, Germany, 7 September 2026</p><div><p>Signature:</p><img src="/reimbursement/coordinator-signature.png" alt="Signature of Vidit Goyal" className="mt-1 h-20 w-full max-w-64 object-contain object-left" /></div></div><div className="space-y-3"><p className="font-bold">For the Partner</p><p>Organisation: {form.partnerName || <span className="text-slate-400">[entered above]</span>}</p><p>Name: {form.legalRepresentativeName || <span className="text-slate-400">[entered above]</span>}</p><p>Position: {form.legalRepresentativePosition || <span className="text-slate-400">[entered above]</span>}</p>{input('signerEmail', 'Signer email', { type: 'email', autoComplete: 'email' })}<div className="grid grid-cols-2 gap-2">{input('signaturePlace', 'Place')} {input('signatureDate', 'Date', { type: 'date', max: today() })}</div><div className="rounded border p-3"><p className="mb-2 font-semibold">Signature for the Partner *</p><SignaturePad onChange={setSignature} disabled={busy} /></div></div></div>
  </article><label className="mx-auto flex max-w-5xl items-start gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm"><input type="checkbox" required checked={declaration} onChange={event => setDeclaration(event.target.checked)} className="mt-1 h-4 w-4 accent-emerald-700" /><span>I confirm that I personally completed and signed this form, that the information is correct, and that I agree to every provision. The signing time, masked IP address and browser/device information will be recorded in the signed PDF.</span></label>{error && <p role="alert" className="mx-auto max-w-5xl rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error}</p>}<div className="mx-auto flex max-w-5xl justify-end"><Button type="submit" size="lg" disabled={busy || !signature || !declaration}><Send className="mr-2 h-4 w-4" />{busy ? 'Submitting…' : 'Submit signed agreement'}</Button></div></form>;
}

function DocRow({ label, children }: { label: string; children: React.ReactNode }) { return <><div className="border-b bg-sky-100 p-2 font-semibold">{label}</div><div className="border-b p-2">{children}</div></>; }
function DocInput({ label, id, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; id: string }) { return <label className="block space-y-1"><span className="block font-semibold">{label} *</span><input id={id} required {...props} className="w-full rounded border border-slate-400 bg-white px-2 py-1.5 outline-none focus:border-sky-700 focus:ring-1 focus:ring-sky-700" /></label>; }
